const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const goals=[['TODAY','主砲を一段進める','今日の実行可能な最小単位へ。'],['THIS WEEK','前進を複数回残す','連続ではなく累積と復帰を評価。'],['THIS MONTH','動く成果物を1つ増やす','現実に残ったものを見る。'],['3 MONTHS','日常運用を定着','司令室を意思決定に使う。'],['6 MONTHS','主要案件を運用段階へ','詳細は公開版では伏せる。'],['1 YEAR','自由時間を増やす構造','仕事だけに人生を吸わせない。'],['3 YEARS','価値観を実行する生活','音楽、移動、家族、自分の時間。'],['5 YEARS','後悔を減らす人生構造','資産・収入数値は非表示。']];
const tasks=[{id:1,t:'主砲を1ステップ進める',c:'本線',p:'最重要',m:'25分',today:1,d:0},{id:2,t:'Life Command Centerの試作を確認する',c:'Life OS',p:'重要',m:'15分',today:1,d:0},{id:3,t:'音楽の火を消さない',c:'音楽',p:'小さく継続',m:'1〜15分',today:1,d:1},{id:4,t:'今週の予定を現実的に組み直す',c:'生活',p:'通常',m:'20分',today:0,d:0}];
const ledger=[{id:'LCC-001',date:'2026-07-14',cat:'その他',title:'Life Command Center 暫定ロードマップ',theme:'人生設計',status:'正本候補',sum:'原点、役割、必要機能、技術ロードマップを一本にまとめた地図。',file:'Life_OS/00_ROADMAP/000_Life_Command_Center_暫定ロードマップ.md'},{id:'LCC-002',date:'2026-08-06',cat:'ルール',title:'保存台帳運用ルール',theme:'情報管理',status:'有効',sum:'一件の単位、正本と索引の分離、分類、関連ファイルの扱いを定義。',file:'Life_OS/01_PRACTICES/002_保存台帳運用ルール.md'},{id:'LCC-003',date:'2026-08-06',cat:'日記',title:'とにかく進める',theme:'実行',status:'保存済み',sum:'完璧を求めず、まず一手を残すことを確認した記録。',file:'Life_OS/03_RAW_LOGS/公開用サンプル.md'},{id:'LCC-004',date:'2026-07-15',cat:'気付き',title:'優しさは残す。服従は外す。',theme:'自分軸',status:'採用',sum:'他者への配慮と、自分の拒否権・再判断権・離脱権を分離する。',file:'Life_OS/00_CONCEPT/公開用サンプル.md'},{id:'LCC-005',date:'2026-08-06',cat:'ルール',title:'戦略的ジャーナリング運用ルール',theme:'ジャーナリング',status:'有効',sum:'対話、採用判断、保存の順序を定義する。',file:'Life_OS/01_PRACTICES/001_戦略的ジャーナリング運用ルール.md'},{id:'LCC-006',date:'2026-07-16',cat:'その他',title:'脳内プログラム書き換え 作成ロードマップ',theme:'自己変革',status:'進行中',sum:'共通構造を抽出し、Life OSへ実装するまでの工程。',file:'Life_OS/99_CHECKPOINTS/公開用サンプル.md'}];

document.querySelector('#app').innerHTML=`
<header class="top"><div class="brand"><span class="mark">◆</span><span>LIFE COMMAND CENTER<small>PUBLIC PROTOTYPE · SAFE DATA</small></span></div><nav class="nav"><button class="active" data-view="today">今日</button><button data-view="tasks">やること</button><button data-view="schedule">スケジュール</button><button data-view="goals">目標</button><button data-view="roadmap">人生ロードマップ</button><button data-view="ledger">保存台帳</button></nav><button class="icon" id="refresh">↻</button></header>
<div class="theme-wrap"><div class="themebar"><strong>THEME</strong><button class="theme-btn active" data-theme="A">A 高級ネオン</button><button class="theme-btn" data-theme="B">B ネオン司令室</button><button class="theme-btn" data-theme="C">C サイバーパンク</button><span class="theme-desc" id="themeDesc">A：大人っぽく熱い</span></div></div>
<main class="main">
<section class="view active" id="today"><div class="head"><div><div class="ey">TODAY · EXECUTION DECK</div><h1>今日を、人生へ接続する。</h1><p>全部やる必要はない。方向を失わず、最重要の一手を現実へ置く。</p></div><span class="badge">SYSTEM ONLINE</span></div><div class="grid today-grid"><article class="panel hero"><div><div class="status"><span class="dot"></span>TODAY'S MAIN MISSION</div><h2>未来を変えるのは、<em>今日の一手</em>です。</h2><p>現在の主砲を一段だけ前へ進める。完璧ではなく、現実に残る前進を選ぶ。</p></div><div><button class="mission" id="mission">主砲を1ステップ進めた</button><span class="muted" id="missionStat">未完了 · 25分</span></div></article><div class="stack"><section class="panel pad"><div class="title"><h3>今日の状態</h3><span class="badge">負荷は適正</span></div><div class="metrics"><div class="metric"><span class="muted">完了</span><b id="doneCount">1 / 4</b><div class="bar"><i id="todayBar" style="--v:25%"></i></div></div><div class="metric"><span class="muted">利用可能時間</span><b>2.5h</b></div><div class="metric"><span class="muted">累積前進</span><b>38</b></div><div class="metric"><span class="muted">復帰成功</span><b>7</b></div></div></section><section class="panel pad"><div class="title"><h3>今日の予定</h3></div><div class="agenda"><div><time>19:30</time><section><b>帰宅・リセット</b><span class="muted">食事、入浴、準備</span></section><span class="badge">生活</span></div><div><time>21:00</time><section><b>主砲の1ステップ</b><span class="muted">25分だけ着手</span></section><span class="badge hot">最重要</span></div><div><time>22:00</time><section><b>音楽の火を消さない</b><span class="muted">1分でも可</span></section><span class="badge">音楽</span></div></div></section></div></div></section>
<section class="view" id="tasks"><div class="head"><div><div class="ey">ACTION INVENTORY</div><h1>やること</h1><p>脳内の「やらないと」を、選べる現実へ変換する。</p></div><button class="mission" id="addTask">＋ タスク追加</button></div><div class="toolbar"><label class="search">⌕<input id="taskSearch" placeholder="タスクを検索"></label><select class="select" id="taskFilter"><option value="all">すべて</option><option value="today">今日</option><option value="important">重要</option><option value="done">完了</option></select></div><div class="grid task-grid"><section class="panel pad"><div class="title"><h3>実行キュー</h3><span class="muted" id="taskCount"></span></div><div class="tasks" id="taskList"></div></section><aside class="stack"><section class="panel pad"><div class="ey">DECISION FILTER</div><p class="quote">これは死ぬときの後悔を減らすか？</p><span class="muted">価値観 → 本線 → 1ミリの順で絞り込む。</span></section><section class="panel pad"><h3>通常モード</h3><p class="muted">負荷が高い日は、主砲1つだけ残す最低限モードへ。</p><button class="ghost" id="minimal">最低限モードへ</button></section></aside></div></section>
<section class="view" id="schedule"><div class="head"><div><div class="ey">TIME REALITY</div><h1>スケジュール</h1><p>願望ではなく、実際の時間へタスクを置く。</p></div><div class="seg" id="scheduleSeg"><button class="active">日</button><button>週</button><button>月</button></div></div><div class="grid today-grid"><section class="panel pad"><div class="title"><h3>本日のタイムライン</h3><span class="muted">空き時間 2時間30分</span></div><div class="timeline"><div class="time"><time>06:30</time><div><b>起床・朝の準備</b><span class="muted">生活</span></div></div><div class="time"><time>08:00</time><div><b>仕事</b><span class="muted">固定予定</span></div></div><div class="time"><time>19:30</time><div><b>帰宅・回復</b><span class="muted">余白を確保</span></div></div><div class="time"><time>21:00</time><div><b>主砲を1ステップ進める</b><span class="muted">25分</span></div></div><div class="time"><time>22:00</time><div><b>音楽の火を消さない</b><span class="muted">最小1分</span></div></div></div></section><aside class="stack"><section class="panel pad"><div class="title"><h3>過負荷チェック</h3><span class="badge">適正</span></div><p class="muted">計画 1時間40分 / 利用可能 2時間30分</p><div class="bar"><i style="--v:66%"></i></div></section><section class="panel pad"><h3>予定の原則</h3><p class="muted">休息を余った時間にしない。回復時間も予定として確保する。</p></section></aside></div></section>
<section class="view" id="goals"><div class="head"><div><div class="ey">GOAL CHAIN</div><h1>目標</h1><p>今日の一手から5年後まで、一本の因果でつなぐ。</p></div></div><div class="grid goals" id="goalList"></div></section>
<section class="view" id="roadmap"><div class="head"><div><div class="ey">LIFE ROADMAP</div><h1>人生ロードマップ</h1><p>何をするかだけでなく、なぜするのかへ戻る場所。</p></div><span class="badge">公開用・一部伏字</span></div><div class="grid road-grid"><aside class="panel toc"><button data-anchor="origin">原点</button><button data-anchor="mainmission">最大ミッション</button><button data-anchor="rewrite">脳内プログラム</button><button data-anchor="assistant">秘書AI</button><button data-anchor="dashboard">ダッシュボード</button><button data-anchor="rules">迷子防止ルール</button></aside><article class="panel doc"><section id="origin"><div class="ey">0 · ORIGIN</div><h2>最上位の原点</h2><p class="manifest">死ぬときに後悔する人生を選ばない。やりたいことを殺さず、自分の価値観を体現し切る。</p></section><section id="mainmission"><h3>現在の最大ミッション</h3><p>現在の主砲を完成へ運ぶ。公開版では案件名・収益目標・資産目標を <span class="redact"></span> として伏せる。</p><ul><li>今日の勝利条件は、主砲を1ミリでも進めること</li><li>考えるだけで終わらず成果物を残すこと</li><li>止まった場合は復帰した時点で成果とすること</li></ul></section><section id="rewrite"><h3>脳内プログラムの書き換え</h3><p>人の評価や機嫌に行動力を奪われる自動処理を見抜き、自分の価値観と現実的な安全判断へ戻る。</p></section><section id="assistant"><h3>秘書AIの役割</h3><p>現在地を確認し、今日の一手を提示し、脱線を戻し、進捗を見える化する。人生を代わりに決めず、本人が価値観に沿って動けるよう支える。</p></section><section id="dashboard"><h3>ダッシュボードの役割</h3><p>単なるタスク管理ではない。行動と意味と報酬を接続する装置である。</p></section><section id="rules"><h3>迷子防止ルール</h3><ol><li>これは死ぬときの後悔を減らすか</li><li>自分の価値観を体現する方向か</li><li>現在の本線を邪魔していないか</li><li>1ミリに分解できるか</li><li>前進を見える化できるか</li></ol></section></article></div></section>
<section class="view" id="ledger"><div class="head"><div><div class="ey">KNOWLEDGE LEDGER</div><h1>保存台帳</h1><p>GitHubに眠る脳内資産を、見つけて使える状態へ。</p></div></div><div class="toolbar"><label class="search">⌕<input id="ledgerSearch" placeholder="タイトル・内容・ファイル名を検索"></label><select class="select" id="ledgerSort"><option value="new">新しい順</option><option value="old">古い順</option><option value="title">タイトル順</option></select><div class="seg"><button id="cardBtn" class="active">カード</button><button id="tableBtn">一覧</button></div></div><div class="chips"><button class="chip active" data-cat="all">すべて</button><button class="chip" data-cat="日記">日記</button><button class="chip" data-cat="ルール">ルール</button><button class="chip" data-cat="気付き">気付き</button><button class="chip" data-cat="その他">その他</button></div><div id="ledgerMount"></div></section>
</main><nav class="mobile"><button class="active" data-view="today">今日</button><button data-view="tasks">やること</button><button data-view="schedule">予定</button><button data-view="goals">その他</button></nav><div class="back" id="back"></div><aside class="drawer" id="drawer"><button class="close" id="close">×</button><span class="badge" id="dcat"></span><h2 id="dtitle"></h2><p id="dsum"></p><div class="detail" id="details"></div><button class="mission">正本を開く（試作）</button></aside><div class="toast" id="toast"></div>`;

const themeText={A:'A：大人っぽく熱い',B:'B：近未来の司令室',C:'C：派手で覚醒感MAX'};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}
function setTheme(t,notify=false){if(!themeText[t])return;document.body.dataset.theme=t;localStorage.setItem('lcc-theme',t);$('#themeDesc').textContent=themeText[t];$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===t));if(notify)toast('テーマ切替：'+themeText[t])}
$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme,true));setTheme(localStorage.getItem('lcc-theme')||'A');
function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));scrollTo({top:0,behavior:'smooth'})}$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function renderTasks(){const q=$('#taskSearch').value.toLowerCase(),f=$('#taskFilter').value,a=tasks.filter(x=>(!q||`${x.t} ${x.c} ${x.p}`.toLowerCase().includes(q))&&(f==='all'||f==='today'&&x.today||f==='important'&&['最重要','重要'].includes(x.p)||f==='done'&&x.d));$('#taskCount').textContent=a.length+'件';$('#taskList').innerHTML=a.map(x=>`<article class="task ${x.d?'done':''}"><button class="check" data-task="${x.id}">${x.d?'✓':''}</button><div><b>${x.t}</b><div class="meta">${x.c} · ${x.p} · ${x.m}</div></div><span class="badge ${x.p==='最重要'?'hot':''}">${x.today?'今日':'今週'}</span></article>`).join('');$$('[data-task]').forEach(b=>b.onclick=()=>{const x=tasks.find(y=>y.id==b.dataset.task);x.d=!x.d;renderTasks();stats();toast(x.d?'前進を記録しました':'完了を取り消しました')})}
function stats(){const n=tasks.filter(x=>x.today&&x.d).length+(localStorage.getItem('mainDone')==='1'?1:0);$('#doneCount').textContent=n+' / 4';$('#todayBar').style.setProperty('--v',n*25+'%')}
function mission(){const d=localStorage.getItem('mainDone')==='1';$('#mission').classList.toggle('done',d);$('#mission').textContent=d?'✓ 今日の主砲は前進済み':'主砲を1ステップ進めた';$('#missionStat').textContent=d?'完了として記録':'未完了 · 25分'}
$('#mission').onclick=()=>{localStorage.setItem('mainDone',localStorage.getItem('mainDone')==='1'?'0':'1');mission();stats();toast('主砲の状態を更新しました')};$('#taskSearch').oninput=renderTasks;$('#taskFilter').onchange=renderTasks;$('#addTask').onclick=()=>{const t=prompt('追加するタスク名');if(t){tasks.unshift({id:Date.now(),t,c:'未分類',p:'通常',m:'未設定',today:0,d:0});renderTasks();toast('試作タスクを追加しました')}};$('#minimal').onclick=e=>{e.target.textContent=e.target.textContent.includes('最低限')?'通常モードへ戻す':'最低限モードへ';toast('モードを切替（試作）')};
$('#goalList').innerHTML=goals.map(x=>`<article class="goal"><div><strong>${x[0]}</strong><h3>${x[1]}</h3><p>${x[2]}</p></div><span class="muted">次の期間へ接続 →</span></article>`).join('');
let cat='all',mode=localStorage.getItem('ledgerMode')||'card';
function rows(){const q=$('#ledgerSearch').value.toLowerCase(),s=$('#ledgerSort').value,a=ledger.filter(x=>(cat==='all'||x.cat===cat)&&(!q||`${x.title} ${x.sum} ${x.theme} ${x.file}`.toLowerCase().includes(q)));a.sort((x,y)=>s==='title'?x.title.localeCompare(y.title,'ja'):s==='old'?x.date.localeCompare(y.date):y.date.localeCompare(x.date));return a}
function renderLedger(){const a=rows();$('#cardBtn').classList.toggle('active',mode==='card');$('#tableBtn').classList.toggle('active',mode==='table');$('#ledgerMount').innerHTML=mode==='card'?`<div class="cards">${a.map(x=>`<article class="card" data-ledger="${x.id}"><div class="row"><span class="badge">${x.cat}</span><span class="muted">${x.date}</span></div><h3>${x.title}</h3><p class="muted">${x.sum}</p><div class="row"><span class="badge">${x.status}</span><span class="muted">${x.theme}</span></div></article>`).join('')}</div>`:`<div class="tablewrap"><table><thead><tr><th>日付</th><th>タイトル</th><th>分類</th><th>テーマ</th><th>状態</th><th>保存場所</th></tr></thead><tbody>${a.map(x=>`<tr data-ledger="${x.id}"><td>${x.date}</td><td><b>${x.title}</b></td><td>${x.cat}</td><td>${x.theme}</td><td>${x.status}</td><td>${x.file}</td></tr>`).join('')}</tbody></table></div>`;$$('[data-ledger]').forEach(e=>e.onclick=()=>openDrawer(e.dataset.ledger))}
function openDrawer(id){const x=ledger.find(y=>y.id===id);$('#dcat').textContent=x.cat;$('#dtitle').textContent=x.title;$('#dsum').textContent=x.sum;$('#details').innerHTML=[['管理番号',x.id],['登録日',x.date],['テーマ',x.theme],['状態',x.status],['正本区分','Markdown正本'],['保存場所',x.file]].map(z=>`<div><span>${z[0]}</span><b>${z[1]}</b></div>`).join('');$('#drawer').classList.add('open');$('#back').classList.add('open')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#back').classList.remove('open')}$('#close').onclick=closeDrawer;$('#back').onclick=closeDrawer;$('#ledgerSearch').oninput=renderLedger;$('#ledgerSort').onchange=renderLedger;$$('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderLedger()});$('#cardBtn').onclick=()=>{mode='card';localStorage.setItem('ledgerMode',mode);renderLedger()};$('#tableBtn').onclick=()=>{mode='table';localStorage.setItem('ledgerMode',mode);renderLedger()};$$('[data-anchor]').forEach(b=>b.onclick=()=>$('#'+b.dataset.anchor).scrollIntoView({behavior:'smooth'}));$$('#scheduleSeg button').forEach(b=>b.onclick=()=>{$$('#scheduleSeg button').forEach(x=>x.classList.toggle('active',x===b));toast(b.textContent+'表示へ切替（試作）')});$('#refresh').onclick=()=>toast('最新状態を確認しました（試作）');
mission();renderTasks();stats();renderLedger();